version: '3'
networks:
  default:
    external:
      name: vacina.local
    
services:
    nginx:
      image: nginx:alpine
      container_name: api-vacina-nginx
      #working_dir: /application
      volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 89:80
      networks:
         default:
          ipv4_address: 192.168.72.5
    php-fpm:
      build: docker/php-fpm
      #image: php:8.2-fpm
      container_name: api-vacina-php-fpm
      #working_dir: /application
      volumes:
        - .:/var/www/html
      networks:
         default:
          ipv4_address: 192.168.72.6
    database:
      image: mysql:latest
      container_name: api-vacina-database
      volumes:
        - ./docker/database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: borgato
        MYSQL_DATABASE: vacina
      ports:
        - ${DB_PORT}:3306
      networks:
         default:
          ipv4_address: 192.168.72.7
    phpmyadmin:
          image: phpmyadmin
          container_name: api-vacina-phpmyadmin
          environment:
              MYSQL_ROOT_PASSWORD: borgato
              PMA_HOSTS: 192.168.72.7
          restart: unless-stopped
          networks:
            default:
             ipv4_address: 192.168.72.8  
                  
